/* @generated by engine/generate_pages.py */
import Script from "next/script";
import type { Metadata } from "next";
import SnapshotClient from "@/lib/SnapshotClient";
import { loadSnapshot } from "@/lib/loadSnapshot";
import { snapshotMetadata } from "@/lib/snapshotMetadata";

const SLUG = "sqlink-com-home";
const LOCALE = "en";

export const generateMetadata = (): Metadata => snapshotMetadata(SLUG, LOCALE);

export default async function HomePage() {
  const { entry, bodyHtml, widgetProps } = await loadSnapshot(SLUG, LOCALE);

  const jsonLdBlocks = [
    ...(entry.head?.jsonLd ?? []),
    ...(entry.head?.jsonLdSynthesized ?? []),
  ];

  return (
    <>
      {jsonLdBlocks.map((block, i) => (
        <Script
          key={i}
          id={`json-ld-${i}-${SLUG}`}
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: block }}
        />
      ))}
      {entry.fontPreloads?.map((href) => (
        <link key={href} rel="preload" href={href} as="font" crossOrigin="anonymous" />
      ))}
      {entry.imagePreloads?.map((preload) => (
        <link
          key={preload.href}
          rel="preload"
          href={preload.href}
          as="image"
          type={preload.type}
          imageSrcSet={preload.imagesrcset}
          fetchPriority="high"
        />
      ))}
      {/* SSR snapshot CSS so downloads start during HTML parse — big LCP win. */}
      {entry.css.map((href) => (
        <link key={href} rel="stylesheet" href={href} />
      ))}
      {/*
        Inline script runs during HTML parse — before CSS blocks rendering —
        so the body has no-margin-top from the very first paint.
        SnapshotClient cleanup removes it on SPA navigation away from home.
      */}
      {/* eslint-disable-next-line @next/next/no-sync-scripts */}
      <script dangerouslySetInnerHTML={{ __html: `document.body.classList.add('no-margin-top')` }} />
      {/*
        Constrain hero slider to one slide height before slick.js initialises.
        The wrapper already has overflow:hidden in CSS; without a height all 3
        uninitialised slides stack vertically. Scoped to .hp_sq-slider__wrapper so
        it does not bleed to other pages during SPA navigation.
      */}
      <style>{`
        .hp_sq-slider__wrapper { height: 780px; }
        @media (max-width: 767px) { .hp_sq-slider__wrapper { height: 520px; } }
      `}</style>
      <SnapshotClient entry={entry} bodyHtml={bodyHtml} widgetProps={widgetProps} />
    </>
  );
}

export const dynamic = "force-static";
