/* @generated by engine/generate_pages.py */
import Script from "next/script";
import type { Metadata } from "next";
import SnapshotClient from "@/lib/SnapshotClient";
import { loadSnapshot } from "@/lib/loadSnapshot";
import { snapshotMetadata } from "@/lib/snapshotMetadata";

const SLUG = "sqlink-com-hightechjob";
const LOCALE = "en";

export const generateMetadata = (): Metadata => snapshotMetadata(SLUG, LOCALE);

export default async function HightechjobPage() {
  const { entry, bodyHtml, widgetProps } = await loadSnapshot(SLUG, LOCALE);

  const jsonLdBlocks = [
    ...(entry.head?.jsonLd ?? []),
    ...(entry.head?.jsonLdSynthesized ?? []),
  ];

  return (
    <>
      {jsonLdBlocks.map((block, i) => (
        <Script
          key={i}
          id={`json-ld-${i}-${SLUG}`}
          type="application/ld+json"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: block }}
        />
      ))}
      {entry.fontPreloads?.map((href) => (
        <link key={href} rel="preload" href={href} as="font" crossOrigin="anonymous" />
      ))}
      {entry.imagePreloads?.map((preload) => (
        <link
          key={preload.href}
          rel="preload"
          href={preload.href}
          as="image"
          type={preload.type}
          imageSrcSet={preload.imagesrcset}
          fetchPriority="high"
        />
      ))}
      {/* SSR snapshot CSS so downloads start during HTML parse — big LCP win.
          Google Fonts URLs are excluded: next/font/google self-hosts Heebo. */}
      {entry.css
        .filter((href) => !href.includes("fonts.googleapis.com"))
        .map((href) => (
          <link key={href} rel="stylesheet" href={href} />
        ))}
      {/* Add no-margin-top before hydration so body margin is removed from first paint,
          allowing the transparent header to overlay the hero banner (same pattern as home page). */}
      {/* eslint-disable-next-line @next/next/no-sync-scripts */}
      <script dangerouslySetInnerHTML={{ __html: `document.body.classList.add('no-margin-top')` }} />
      <SnapshotClient entry={entry} bodyHtml={bodyHtml} widgetProps={widgetProps} />
    </>
  );
}

export const dynamic = "force-static";
